#!/usr/bin/env bash
#Bash Script that manages manage_my_process.

#When passing the argument "start":
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started

#When passing the argument "stop":
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Displays manage_my_process stopped

#When passing the argument "restart":
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted

#Displays Usage: manage_my_process {start|stop|restart}

F_Containin_PID= "/var/run/my_process.pid"
P= "manage_my_process"
#P stands for the name of the file "manage_my_process"

start () {
if [ -f "$F_Containin_PID" ];
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "running manage_my_process"
    exit 1
fi
    ./manage_my_process &
    touch /var/run/my_process.pid 
    echo "$P started"
}

stop () {
if [ ! -f "$F_Containin_PID" ];
then
    echo "not running manage_my_process"
    exit 1
fi

    kill $F_Containin_PID || {echo "Failed to stop $P"; exit 1;}
    rm -f "$F_Containin_PID"
    echo "$P stopped"
}

restart (){

    stop
    start
    echo "$P restarted"
}

if [ "$1" = "start" ]; then
    start
elif [ "$1" = "stop" ]; then
    stop
elif [ "$1" = "restart" ]; then
    restart
else
    echo "Usage: $P {start|stop|restart}"
    exit 1
fi
